// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbfwklibckljutucscmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZndrbGliY2tsanV0dWNzY21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjcyNzQsImV4cCI6MjA2MjkwMzI3NH0.swzngCUanO1WOAa4NAUPzxRsXRolYJAHOcbqZORkI9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);